apps:
  - name: discord-app-bot
    script: dist/index.js
    interpreter_args: --enable-source-maps
    log_date_format: '[[]YYYY-MM-DD [at] HH:mm:ss]'
    combine_logs: true
    error_file: logs/errors.log
    out_file: logs/discord-app-bot.log